<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Claim Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-12-21T09:55:01</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f03223aa-00fd-41cd-89bb-da9c99fd35c1</testSuiteGuid>
   <testCaseLink>
      <guid>83613d8f-c483-4422-a47b-5380d196d7ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create Claim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11701ff7-60d4-412d-9e64-1972b8011816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec594875-be7f-42bb-bade-5e33dff65567</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54450dd9-760f-4701-a9e6-f0dc9da2067d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23af3537-6b9b-41d0-8fe7-46ed9b92b5c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cbd3c69-d967-4632-bed2-f0cc7bd65639</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create Claim - Negative</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01a50aa4-aa47-428e-81d3-82c3ec3c2c12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d5c3b4-bdd1-4cfc-be97-692924bf6ab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0707473-47fe-4e24-b49f-bb94517554cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a376087-3688-4b85-a104-a795edd28aa7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
