<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_Claimant</name>
   <tag></tag>
   <elementGuidId>cff624ad-505c-4994-8db6-d21d3616c822</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_AssignSaveScreen:Claimant_Name-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_AssignSaveScreen:Claimant_Name-trigger-picker</value>
   </webElementProperties>
</WebElementEntity>
