<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_Relation</name>
   <tag></tag>
   <elementGuidId>927bb4b8-d781-4d70-9cee-ebe821dd4506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Relationship-trigger-picker']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Relationship-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Relationship-trigger-picker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Relationship-trigger-picker&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//div[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Relationship-trigger-picker']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Relationship-triggerWrap']/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relation to Insured'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who became ill?'])[1]/following::div[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Which illness has occured?'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this a condition that was known when the trip was booked?'])[1]/preceding::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//td/div/table/tbody/tr/td/div/table/tbody/tr/td/div/table/tbody/tr[2]/td/div/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
