<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_Who became ill</name>
   <tag></tag>
   <elementGuidId>88c3577b-c666-44c5-a6e2-1983ade61961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Injured_Picker-trigger-picker']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Injured_Picker-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Injured_Picker-trigger-picker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Injured_Picker-trigger-picker&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//div[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Injured_Picker-trigger-picker']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:SpecificDetails:FNOLWizard_TripSpecificDetails_TCOPanelSet:Injured_Picker-triggerWrap']/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who became ill?'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About the incident'])[1]/following::div[14]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relation to Insured'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Which illness has occured?'])[1]/preceding::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
