<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Add Trip</name>
   <tag></tag>
   <elementGuidId>3a917910-4eb7-4e14-8c33-eb82810a9b5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:FNOLWizard_TripDetails_TCOPanelSet_tb:AddTripButton-btnInnerEl']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:FNOLWizard_TripDetails_TCOPanelSet_tb:AddTripButton-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:FNOLWizard_TripDetails_TCOPanelSet_tb:AddTripButton-btnInnerEl</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//span[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:FNOLWizard_TripDetails_TCOPanelSet_tb:AddTripButton-btnInnerEl']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//span[@id='FNOLWizard:AutoWorkersCompWizardStepSet:FNOLWizard_CancellationDetails_TCOScreen:FNOLWizard_TripGenericDetails_TCOPanelSet:FNOLWizard_TripDetails_TCOPanelSet_tb:AddTripButton-btnEl']/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is the reason for the trip being cancelled?'])[1]/following::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Cause'])[1]/following::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About the incident'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//tr[5]/td/div/table/tbody/tr/td/div/div/div/a/span/span/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
